source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'redis'
gem 'socket.io-rails'
gem 'responders'
gem 'materialize-sass'

group :doc do
  gem 'sdoc', '~> 0.4.0' 
end

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
end

